site_name: APACAI Docs
plugins:
  - glightbox
  - search
copyright: "&copy; APACAI, Inc."
extra_css:
  - assets/css/extra.css
extra:
  analytics:
    provider: google
    property: G-QM8EDPSCB6
  social:
    - icon: fontawesome/solid/house
      link: https://www.apac.ai
    - icon: fontawesome/brands/discord
      link: https://discord.gg/gnWRz88eym
    - icon: fontawesome/brands/github
      link: https://github.com/kyegomez/APACAI/
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/APACAI/
theme:
    name: material
    custom_dir: docs/overrides
    logo: assets/img/APACAI-logo.png
    palette:
      # Palette toggle for light mode
    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    features:
        - content.code.copy
        - content.code.annotate
        - navigation.tabs
        - navigation.sections
        - navigation.expand
        - navigation.top
        - announce.dismiss
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - tables
  - def_list
  - footnotes
nav:
- Home:
    - Overview: "index.md"
    - Contributing: "contributing.md"
    - FAQ: "faq.md"
- APACAI Framework:
  - Overview: "APACAI/index.md"
  - Tools:
      - Overview: "APACAI/tools/index.md"
      - Tool Memory: "APACAI/tools/tool-memory.md"
      - Building Custom Tools: "APACAI/tools/custom-tools.md"
  - Governance:
      - Developer Guidelines: "APACAI/governance/DEVELOPER.md"
      - Roadmap: "APACAI/governance/ROADMAP.md"
      - Sales Strategy: "APACAI/governance/SALES.md"
  - SOPS:
    - Engineering:
      - Clean Code: "APACAI/sops/Engineering/CleanCode.md"
      - Documentation: "APACAI/sops/Engineering/Documentation.md"
      - Model Deployment: "APACAI/sops/Engineering/ModelDeployment/README.md"
      - Systems Thinking: "APACAI/sops/Engineering/SystemsThinking.md"
    - Sales:
      - Go-to-Market Strategy: "APACAI/sops/SALES/GTM.md"
  - Ideas:
    - Overview: "APACAI/ideas/README.md"
  - Presentations:
    - Agora: 
      - Agora Presentation: "APACAI/presentations/Agora/agora-compressed.pdf"
  - Resources:
    - Books: "APACAI/resources/BOOKS.md"
  - Values:
    - Overview: "APACAI/values/README.md"