site_name: APACAI Docs
plugins:
  - glightbox
  - search
copyright: "&copy; APACAI, Inc."
extra_css:
  - assets/css/extra.css
extra:
  analytics:
    provider: google
    property: G-QM8EDPSCB6
  social:
    - icon: fontawesome/solid/house
      link: https://www.apac.ai
    - icon: fontawesome/brands/discord
      link: https://discord.gg/gnWRz88eym
    - icon: fontawesome/brands/github
      link: https://github.com/kyegomez/APACAI/
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/APACAI/
theme:
    name: material
    custom_dir: docs/overrides
    logo: assets/img/APACAI-logo.png
    palette:
      # Palette toggle for light mode
    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    features:
        - content.code.copy
        - content.code.annotate
        - navigation.tabs
        - navigation.sections
        - navigation.expand
        - navigation.top
        - announce.dismiss
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - tables
  - def_list
  - footnotes
nav:
- Home:
    - Overview: "index.md"
    - Contributing: "contributing.md"
    - FAQ: "faq.md"
- APACAI Framework:
  - Overview: "APACAI/index.md"
  - Services:
    - Pipelines: "APACAI/structures/pipelines.md"
    - Agents: "APACAI/structures/agents.md"
    - Workflows: "APACAI/structures/workflows.md"
    - Prompt Drivers: "APACAI/structures/prompt-drivers.md"
    - Conversation Memory: "APACAI/structures/conversation-memory.md"
    - Rulesets: "APACAI/structures/rulesets.md"
    - Events: "APACAI/structures/events.md"
  - Tools:
      - Overview: "APACAI/tools/index.md"
      - Tool Memory: "APACAI/tools/tool-memory.md"
      - Building Custom Tools: "APACAI/tools/custom-tools.md"
  - Data:
    - Overview: "APACAI/data/index.md"
    - Artifacts: "APACAI/data/artifacts.md"
    - Embeddings: "APACAI/data/embeddings.md"
    - Chunkers: "APACAI/data/chunkers.md"
    - Loaders: "APACAI/data/loaders.md"
    - Query Engines: "APACAI/data/query-engines.md"
    - Summary Engines: "APACAI/data/summary-engines.md"
    - Vector Stores: "APACAI/data/vector-stores.md"
    - SQL Drivers: "APACAI/data/sql-drivers.md"
- Examples:
    - Overview: "examples/index.md"
    - Agents:
      - Talk to Redshift: "examples/talk-to-redshift.md"
      - Talk to a Webpage: "examples/talk-to-a-webpage.md"
      - Talk to a PDF: "examples/talk-to-a-pdf.md"
    - Data:
      - Load and Query Pinecone: "examples/load-and-query-pinecone.md"
      - Load and Query Marqo: "examples/load-query-and-chat-marqo.md"
      - Query a Webpage: "examples/query-webpage.md"
    - Misc:
        - Count Tokens: "examples/count-tokens.md"
        - Using Text Generation Web UI: "examples/using-text-generation-web-ui.md"
        - Storing Conversation Memory in DynamoDB: "examples/store-conversation-memory-in-dynamodb.md"