site_name: APACAI Docs
plugins:
  - glightbox
  - search
copyright: "&copy; APACAI, Inc."
extra_css:
  - assets/css/extra.css
extra:
  # analytics:
  #   provider: google
  #   property: G-QM8EDPSCB6
  social:
    - icon: fontawesome/solid/house
      link: https://www.apac.ai
    - icon: fontawesome/brands/discord
      link: https://discord.gg/gnWRz88eym
    - icon: fontawesome/brands/github
      link: https://github.com/kyegomez/apacai
theme:
    name: material
    custom_dir: docs/overrides
    logo: docs/assets/img/APACAI-logo.png
    palette:
      # Palette toggle for light mode
    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    features:
        - content.code.copy
        - content.code.annotate
        - navigation.tabs
        - navigation.sections
        - navigation.expand
        - navigation.top
        - announce.dismiss
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - tables
  - def_list
  - footnotes
nav:
  - Home:
    - Overview: "index.md"
    - Contributing: "contributing.md"
    - FAQ: "faq.md"
  - APACAI:
    - Overview: "tanlecontents.md"
    - Governance:
      - Developer Guidelines: "governance/DEVELOPER.md"
      - Roadmap: "governance/ROADMAP.md"
      - Sales Strategy: "governance/SALES.md"
    - SOPS:
      - Engineering:
        - Clean Code: "apacai/sops/Engineering/CleanCode.md"
        - Documentation: "apacai/sops/Engineering/Documentation.md"
        - Model Deployment: "apacai/sops/Engineering/ModelDeployment/README.md"
        - Systems Thinking: "apacai/sops/Engineering/SystemsThinking.md"
      - Sales:
        - Go-to-Market Strategy: "apacai/sops/SALES/GTM.md"
    - Ideas:
      - Overview: "apacai/ideas/README.md"
    - Presentations:
      - Agora:
        - Agora Presentation: "apacai/presentations/Agora/agora-compressed.pdf"
    - Resources:
      - Books: "apacai/resources/BOOKS.md"
    - Values:
      - Overview: "apacai/values/README.md"
    - BusinessModels:
      - BMAnalysis:
        - ARASAKA: "apacai/BusinessModels/BMAnalysis/ARASAKA.md"
        - ATLAS: "apacai/BusinessModels/BMAnalysis/ATLAS.md"
        - CHOAM: "apacai/BusinessModels/BMAnalysis/CHOAM.md"
        - DUTCHEAST: "apacai/BusinessModels/BMAnalysis/DUTCHEAST.md"
        - HUDSONBAY: "apacai/BusinessModels/BMAnalysis/HUDSONBAY.md"
        - LEX: "apacai/BusinessModels/BMAnalysis/LEX.md"
        - NVIDIA: "apacai/BusinessModels/BMAnalysis/NVIDIA.md"
        - TSCM: "apacai/BusinessModels/BMAnalysis/TSCM.md"
        - TYRELL: "apacai/BusinessModels/BMAnalysis/TYRELL.md"
        - USSTEEL: "apacai/BusinessModels/BMAnalysis/USSTEEL.md"
        - WALMART: "apacai/BusinessModels/BMAnalysis/WALMART.md"
        - WAYNE: "apacai/BusinessModels/BMAnalysis/WAYNE.md"
        - WEYLAND: "apacai/BusinessModels/BMAnalysis/WEYLAND.md"
      - FuturisticBM:
        - FuturisticBM Overview: "apacai/BusinessModels/FuturisticBM/README.md"
    - Contracts:
      - CloudProviderPartnership:
        - AgoraCloudPartner: "apacai/Contracts/CloudProviderPartnership/AgoraCloudPartner.md"
    - Acquisitions:
      - Overview: "apacai/Acquisitions/README.md"
    - Brand:
      - LogBook:
        - Overview: "apacai/Brand/LogBook/README.md"
        - APACAI-BANNER Copy: "apacai/APACBrand/LogBook/APACAI-BANNER copy.png"
        - APACAI-PARTNERS: "apacai/Brand/LogBook/APACAI-PARTNERS.png"
        - Swarms Banner: "apacai/Brand/LogBook/swarmsbanner.png"
      - MAIDaily: "apacai/Brand/MAIDaily.md"
    - Financials: "apacai/Financials/README.md"
    - Services:
      - Overview: "apacai/Services/README.md"
      - Current:
        - Frameworks:
          - Swarms:
            - BM: "apacai/Services/Current/Frameworks/Swarms/BM.md"
            - DESIGN_PHILOSOPHY: "apacai/Services/Current/Frameworks/Swarms/DESIGN_PHILOSOPHY.md"
            - Distribution: "apacai/Services/Current/Frameworks/Swarms/Distribution.md"
            - FLYWHEEL: "apacai/Services/Current/Frameworks/Swarms/FLYWHEEL.md"
            - PURPOSE: "apacai/Services/Current/Frameworks/Swarms/PURPOSE.md"
            - README: "apacai/Services/Current/Frameworks/Swarms/README.md"
            - ROADMAP: "apacai/Services/Current/Frameworks/Swarms/ROADMAP.md"
            - SALES: "apacai/Services/Current/Frameworks/Swarms/SALES.md"
        - ModelSuites:
          - Cybertron:
            - Cybertron: "apacai/Services/Current/ModelSuites/Cybertron/README.md"
        - Models:
          - Andromeda:
            - Andromeda.pdf: "apacai/Services/Current/Models/Andromeda/Andromeda.pdf"
            - Overview: "apacai/Services/Current/Models/Andromeda/README.md"
          - Kosmos:
            - CASHFLOWS: "apacai/Services/Current/Models/Kosmos/CASHFLOWS.md"
            - GTM: "apacai/Services/Current/Models/Kosmos/GTM.md"
            - MONETIZATION: "apacai/Services/Current/Models/Kosmos/MONETIZATION.md"
            - Nexus: "apacai/Services/Current/Models/Kosmos/Nexus.md"
            - Overview: "apacai/Services/Current/Models/Kosmos/README.md"
        - Platforms:
          - AthenaBrowser:
            - BusinessModel: "apacai/Services/Current/Platforms/AthenaBrowser/BusinessModel.md"
            - EnterprisePlan: "apacai/Services/Current/Platforms/AthenaBrowser/EnterprisePlan.md"
            - README: "apacai/Services/Current/Platforms/AthenaBrowser/README.md"
            - ValueProposition: "apacai/Services/Current/Platforms/AthenaBrowser/ValueProposition.md"
          - TheDomain:
            - Overview: "apacai/Services/Current/Platforms/TheDomain/README.md"
        - Transcend:
          - Overview: "apacai/Services/Current/Transcend/README.md"
          - transcend.pdf: "apacai/Services/Current/Transcend/transcend.pdf"
      - Futuristic:
        - AthenaOS:
          - IDEAS: "apacai/Services/Futuristic/AthenaOS/IDEAS.md"
          - Overview: "apacai/Services/Futuristic/AthenaOS/README.md"
        - Nanomachines:
          - Overview: "apacai/Services/Futuristic/Nanomachines/README.md"
        - FuturisticOverview: "apacai/Services/Futuristic/README.md"
        - SpaceMining:
          - Overview: "apacai/Services/Futuristic/SpaceMining/README.md"
        - SwarmRobotics:
          - Overview: "apacai/Services/Futuristic/SwarmRobotics/README.md"